# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-07 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_auto_20180707_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='image',
            field=models.ImageField(default='org/0.jpg', upload_to='org/%Y/%m', verbose_name='logo'),
        ),
    ]
