# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-25 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_auto_20180707_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='desc',
            field=models.TextField(max_length=200, verbose_name='机构描述'),
        ),
    ]
