# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-03 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20180703_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDirection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_direction', models.CharField(default='', max_length=100, verbose_name='课程方向')),
            ],
            options={
                'verbose_name_plural': '课程方向',
                'verbose_name': '课程方向',
            },
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_direction',
        ),
        migrations.AddField(
            model_name='course',
            name='direction',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.CourseDirection', verbose_name='课程方向'),
        ),
    ]
