# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-04 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_coursecategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.CourseCategory', verbose_name='课程类别'),
        ),
    ]
