# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-04 18:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20180704_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='direction',
        ),
    ]
