# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-04 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_remove_course_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='direction',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.CourseDirection', verbose_name='课程方向'),
        ),
    ]
