# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-07 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_course_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='desc',
            field=models.TextField(max_length=300, verbose_name='课程描述'),
        ),
    ]
