# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-07 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_auto_20180707_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teacher_tell',
            field=models.TextField(default='', max_length=300, verbose_name='老师告诉你'),
        ),
        migrations.AlterField(
            model_name='course',
            name='youneed_know',
            field=models.TextField(default='', max_length=300, verbose_name='课程须知'),
        ),
    ]
