# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-07 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_auto_20180707_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default=0, upload_to='course/%Y/%m', verbose_name='封面图'),
        ),
    ]
