# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-07 12:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_auto_20180707_1153'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursecategory',
            unique_together=set([('direction', 'course_category')]),
        ),
    ]
