# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-07 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_auto_20180707_1253'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursecategory',
            unique_together=set([]),
        ),
    ]
