# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-07 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_auto_20180707_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecategory',
            name='direction',
        ),
        migrations.AddField(
            model_name='coursedirection',
            name='category',
            field=models.ForeignKey(blank=True, max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.CourseCategory', verbose_name='课程类别'),
        ),
    ]
