# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-07 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_auto_20180707_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursedirection',
            name='category',
        ),
        migrations.AddField(
            model_name='coursecategory',
            name='direction',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.CourseDirection', verbose_name='课程方向'),
        ),
    ]
