# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-07 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_auto_20180707_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_category_course', to='courses.CourseCategory', verbose_name='课程类别'),
        ),
        migrations.AlterField(
            model_name='course',
            name='direction',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direction_course', to='courses.CourseCategory', verbose_name='课程方向'),
        ),
    ]
