# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-07 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_auto_20180707_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursecategory',
            old_name='direction',
            new_name='course_direction',
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='courses.CourseCategory', verbose_name='课程类别'),
        ),
        migrations.AlterField(
            model_name='course',
            name='direction',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direction', to='courses.CourseCategory', verbose_name='课程方向'),
        ),
    ]
