# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-07 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_auto_20180707_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursecategory',
            old_name='course_direction',
            new_name='direction',
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.CourseCategory', verbose_name='课程类别'),
        ),
        migrations.AlterField(
            model_name='course',
            name='direction',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.CourseDirection', verbose_name='课程方向'),
        ),
    ]
