# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-07 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_auto_20180707_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedirection',
            name='course_category',
            field=models.CharField(default='', max_length=100, verbose_name='课程类别'),
        ),
        migrations.AlterUniqueTogether(
            name='coursecategory',
            unique_together=set([('direction', 'course_category')]),
        ),
    ]
