# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-07 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_auto_20180707_1404'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursecategory',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='coursedirection',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='coursedirection',
            name='course_category',
        ),
    ]
