# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-26 11:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0032_auto_20180707_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecategory',
            name='direction',
        ),
    ]
