# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-26 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0033_remove_coursecategory_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(default=1, max_length=20, on_delete=django.db.models.deletion.CASCADE, to='courses.CourseCategory', verbose_name='课程类别'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='direction',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='courses.CourseDirection', verbose_name='课程方向'),
        ),
    ]
