# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-02 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0035_coursecategory_direction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecategory',
            name='direction',
        ),
    ]
