# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-24 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commucation', '0008_auto_20181124_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tag',
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(to='commucation.Tag', verbose_name='标签'),
        ),
    ]
