# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-29 13:41
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commucation', '0010_auto_20181129_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', null=True, verbose_name='文章内容'),
        ),
    ]
