# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-21 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commucation', '0013_auto_20181221_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, max_length=100000, null=True, verbose_name='文章内容'),
        ),
    ]
